import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, padding: 10, backgroundColor: '#FFFFFF' },
  // Tablet/POS layout styles
  tabletLayout: {
    flex: 1,
    flexDirection: 'row',
    gap: 16,
  },
  tabletMenuSection: {
    flex: 0.6, // 60% width for menu
    paddingRight: 8,
    overflow: 'hidden',
  },
  tabletCartSection: {
    flex: 0.4, // 40% width for cart
    borderLeftWidth: 1,
    borderLeftColor: '#E5E7EB',
    paddingLeft: 16,
    backgroundColor: '#FAFAFA',
  },
  // Search + category header (used in renderMenuItems)
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 10,
  },
  tabletSearchBar: {
    paddingHorizontal: 4,
    marginBottom: 20,
    gap: 12,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    minWidth: 0, // Prevents flex item from overflowing
  },
  tabletSearchInputWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchInput: {
    flex: 1,
    color: '#111827',
    fontSize: 14,
    paddingVertical: 0,
    minWidth: 0, // Prevents text input from overflowing
  },
  tabletSearchInput: {
    fontSize: 15,
  },
  clearButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    marginLeft: 10,
  },
  clearText: {
    color: '#111827',
    fontWeight: '700',
    fontSize: 12,
  },
  countBadge: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexShrink: 0,
  },
  categoryArea: {
    marginBottom: 12,
  },
  tabletCategoryArea: {
    minHeight: 80,
    marginBottom: 20,
  },
  categoryList: {
    flexGrow: 0,
  },
  categoryListContent: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tabletCategoryListContent: {
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  tabletCategoryPill: {
    paddingHorizontal:  14,
    paddingVertical: 8,
    minHeight: 38,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    marginRight: 10,
    minWidth: 68,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(17,24,39,0.06)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  tabletCategoryPillActive: {
    backgroundColor: '#FF6B6B',
    borderColor: 'rgba(255,107,107,0.12)',
    shadowOpacity: 0.08,
    elevation: 2,
  },
  categoryPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(17,24,39,0.06)',
  },
  categoryPillActive: {
    backgroundColor: '#FF6B6B',
    borderColor: 'rgba(255,107,107,0.12)',
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111827',
  },
  categoryLabelActive: { color: '#FFFFFF' },
  tabletCategoryLabel: {
    fontSize: 14,
  },
  menuList: { paddingBottom: 160 },
  tabletMenuList: {
    paddingBottom: 220,
  },
  tabletMenuColumnWrapper: {
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  menuCard: {
    flexDirection: 'row',
    padding: 16,
    borderRadius:  16,
    backgroundColor: '#FFFFFF',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB', // light neutral border that follows the radius
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius:  12,
    elevation: 2,
  },
  tabletMenuCard: {
    flex: 1,
    marginHorizontal: 4,
    minWidth: 0, // Prevents overflow
    padding: 12, // Slightly smaller padding for tablet
  },
  menuImageWrapper: { marginRight:  14, flexShrink: 0 },
  tabletMenuImageWrapper: { marginRight: 12 },
  availabilityDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#27AE60',
    position: 'absolute',
    top: -4,
    right: -4,
    zIndex: 2,
  },
  availabilityDotOff: { backgroundColor: '#D1D5DB' },
  menuImage: { width: 90, height: 90, borderRadius: 14, backgroundColor: '#F3F4F6', resizeMode: 'cover' },
  tabletMenuImage: { width: 80, height: 80 },
   placeholder: { alignItems: 'center', justifyContent: 'center' },
  placeholderText: { color: '#6B7280', fontSize: 12 },
  menuInfo: { flex: 1, minWidth: 0 }, // Prevents overflow
  menuTitle: { fontSize: 16, fontWeight: '800', color: '#111827' },
  tabletMenuTitle: { fontSize: 17 },
  menuMeta: { marginTop: 4, color: '#6B7280', fontSize: 13 },
  tabletMenuMeta: { fontSize: 13 },
  menuFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14 },
  menuPrice: {
    fontSize: 16,
    fontWeight: '900',
    color: '#FF6B6B',    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  tabletMenuPrice: { fontSize: 17 },
  qtyPill: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FF6B6B',
    backgroundColor: '#FFFFFF',
  },
  tabletQtyPill: {},
  cartQtyPill: { marginHorizontal: 12 },
  qtyPillButton: { paddingHorizontal: 12, paddingVertical:  4, fontSize: 18, fontWeight: '700', color: '#FF6B6B' },
  tabletQtyPillButton: {},
  qtyPillValue: { minWidth: 26, textAlign: 'center', fontWeight: '700', color: '#111827' },
  tabletQtyPillValue: {},
   addBadge: {
    backgroundColor: 'transparent',
    borderRadius: 10, // match menuCard radius
    paddingVertical: 6,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#FF6B6B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabletAddBadge: {},
  addBadgeText: {
    color: '#FF6B6B',
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  tabletAddBadgeText: {},
  cartSummaryBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 25,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 28,
    backgroundColor: '#FF6B6B',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
  },
  cartSummaryItems: { color: '#FFFFFF', fontSize: 13, letterSpacing: 0.6, textTransform: 'uppercase' },
  cartSummaryTotal: { color: '#FFFFFF', fontSize: 18, fontWeight: '800' },
  cartSummaryCta: { color: '#FFFFFF', fontWeight: '800', fontSize: 15 },
  fabCart: {
    position: 'absolute',
    right: 20,
    bottom: 28,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    zIndex: 1100,
  },
  fabCartText: { color: '#fff', fontWeight: '800' },

  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.2)' },
  keyboardAvoid: { flex:  1, justifyContent: 'center' },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    padding: 18,
    borderRadius: 14,
    width: '95%',
    maxWidth: 700,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  tabletModalContent: {
    padding: 24,
    borderRadius: 16,
    maxWidth: 800,
  },
  tabletScrollContent: {
    paddingVertical: 30,
  },
  tabletModalTitle: {
    fontSize: 22,
    marginBottom: 8,
  },
  modalHeader: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#FF6B6B',
    alignItems: 'flex-start',
  },
  modalTitle: { fontSize: 18, fontWeight: '800', color: '#111827' },
  input: { borderWidth: 1, borderColor: '#E5E7EB', padding: 10, marginBottom: 10, borderRadius: 5, color: '#111827', backgroundColor: '#FFFFFF' },
  serviceChargeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between' },
  cancelButton: { backgroundColor: '#F3F4F6', padding: 10, borderRadius: 5 },
  cancelText: { color: '#111827' },
  submitButton: {
    backgroundColor: '#FF6B6B',
    padding: 10,
    borderRadius: 5
  },
  submitButtonDisabled: {
    backgroundColor: '#FCA5A5',
    opacity: 0.6,
  },
  submitText: { color: '#FFFFFF' },
  billSummary: { marginBottom: 20 },
  totalText: { fontWeight: 'bold', fontSize: 18, color: '#111827' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: height > 600 && width > 300 ? 30 : 18,
    paddingHorizontal: width > 400 ? 12 : 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  backButton: { padding: 5 },
  backText: { fontSize: width > 400 ? 16 : 14, color: '#FF6B6B' },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: width > 400 ? 26 : 22, fontWeight: '700', marginHorizontal: 10, color: '#111827' },
  spacer: { width: 50 },

  // Add missing styles:
  cancelButtonAlt: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancelTextAlt: { color: '#111827', fontWeight: '700' },
  submitButtonAlt: {
    flex: 1,
    backgroundColor: '#FF6B6B',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  submitTextAlt: { color: '#FFFFFF', fontWeight: '800' },

  // Ongoing drawer styles
  ongoingToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#FF6B6B',
    borderWidth: 1,
    borderColor: '#FB7185',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
    flexShrink: 0,
  },
  tabletOngoingToggle: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  ongoingToggleText: {
    color: '#FFFFFF',
    fontWeight: '800',
    marginRight: 8,
    fontSize: 14,
    letterSpacing: 0.4,
  },
  tabletOngoingToggleText: {
    fontSize: 15,
  },
  ongoingBadge: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    minWidth: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ongoingBadgeText: {
    color: '#FF6B6B',
    fontWeight: '900',
    fontSize: 12,
  },
  ongoingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    zIndex: 900,
  },
  ongoingDrawer: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: '100%',
    width: 360,
    maxWidth: '100%',
    backgroundColor: '#fff',
    zIndex: 950,
    shadowColor: '#000',
    shadowOffset: { width: -6, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    borderLeftWidth: 1,
    borderLeftColor: '#F3F4F6',
  },
  tabletOngoingDrawer: {
    width: 420,
  },
  ongoingDrawerOpen: { transform: [{ translateX: 0 }] },
  ongoingDrawerClosed: { transform: [{ translateX: 400 }] },
  ongoingHeader: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#F3F4F6', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  ongoingTitle: { fontWeight: '800', fontSize: 16 },
  ongoingOrderCard: { borderWidth: 1, borderColor: '#F3F4F6', borderRadius: 10, padding: 12, marginBottom: 12, backgroundColor: '#FFFFFF' },
  ongoingStatusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, alignItems: 'center' },
  ongoingActionBtn: { flex: 1, padding: 10, borderRadius: 8, borderWidth: 1, borderColor: '#E5E7EB', alignItems: 'center' },
  ongoingActionText: { color: '#111827', fontWeight: '700' },
  refreshBtn: { backgroundColor: '#111827', borderColor: '#111827' },
  refreshBtnText: { color: '#FFFFFF' },
  closeBtn: { backgroundColor: '#FF6B6B', borderColor: '#FF6B6B' },
  closeBtnText: { color: '#FFFFFF' },

  // Finalize modal styles
  finalizeModalScroll: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  finalizeModalContent: {
    marginHorizontal: 0,
    maxHeight: height * 0.85,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  finalizeModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 16,
    textAlign: 'left',
  },
  finalizeLabel: {
    marginTop: 12,
    marginBottom: 6,
    fontWeight: '700',
    color: '#111827',
    fontSize: 14,
  },
  finalizeDropdownTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  finalizeDropdownText: {
    flex: 1,
    color: '#111827',
    fontSize: 15,
  },
  finalizeDropdownIcon: {
    color: '#6B7280',
    marginLeft: 8,
  },
  finalizeInput: {
    fontSize: 15,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  finalizeInputDisabled: {
    backgroundColor: '#F3F4F6',
    color: '#9CA3AF',
  },
  finalizeChangeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  finalizeChangeLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#374151',
  },
  finalizeChangeValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#059669',
  },
  finalizeDateText: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 16,
    textAlign: 'left',
  },
  finalizeButtonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  finalizeCancelButton: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  finalizeCancelText: {
    color: '#374151',
    fontWeight: '700',
    fontSize: 15,
    textAlign: 'center',
  },
  finalizeConfirmButton: {
    flex: 1,
    backgroundColor: '#FF6B6B',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    minHeight: 48,
  },
  finalizeConfirmButtonDisabled: {
    opacity: 0.6,
  },
  finalizeConfirmText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
    textAlign: 'center',
  },

  // Other missing styles
  label: { marginTop: 12, marginBottom: 6, fontWeight: '700', color: '#111827' },
  summaryText: { marginVertical: 4, color: '#111827' },
  summarySubtitle: { marginTop: 12, fontWeight: '700', color: '#111827' },
  priceSummaryContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  priceSummaryTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 12,
  },
  priceSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  priceSummaryLabel: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '600',
  },
  priceSummaryValue: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '600',
  },
  priceSummaryTotal: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 2,
    borderTopColor: '#FF6B6B',
  },
  priceTotalLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  priceTotalValue: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FF6B6B',
  },
  segmentedControl: {
    flexDirection: 'row',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    marginBottom: 10,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  segmentButtonActive: {
    backgroundColor: '#FF6B6B',
  },
  segmentButtonText: {
    color: '#111827',
    fontWeight: '700',
  },
  segmentButtonTextActive: {
    color: '#FFFFFF',
  },
  paymentDropdown: {
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginTop: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  paymentDropdownOption: {
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  paymentMethodTextActive: { color: '#FF6B6B', fontWeight: '800' },
  paymentMethodText: { color: '#111827', fontWeight: '700' },
  finalizeFieldsContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  finalizeCenteredBox: {
    width: '88%',
    maxWidth: 480,
    backgroundColor: '#fff',
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
});
